# Generated by Django 2.1.1 on 2018-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('voter_id', models.IntegerField(unique=True)),
                ('pan_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=264)),
                ('location', models.CharField(max_length=264)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('vote_flag', models.BooleanField(default=True)),
            ],
        ),
    ]
