# Generated by Django 2.1.1 on 2018-09-21 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_auto_20180921_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='Age',
            field=models.IntegerField(default=23, validators=[django.core.validators.MaxValueValidator(110)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voters',
            name='user_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voters',
            name='pan_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='voters',
            name='vote_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voters',
            name='voter_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
