# Generated by Django 2.1.1 on 2018-09-21 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('pan_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=264)),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('employee_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
